# Generated by Django 2.2.14 on 2023-11-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231124_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='full_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Clothes'), ('M', 'Mobiles and Tablets'), ('H', 'Home Appliances'), ('W', 'Wearables')], max_length=2),
        ),
    ]
