# Generated by Django 2.2.14 on 2023-11-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231125_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='full_description',
            field=models.TextField(blank=True, default='No Additional Descriptions Available'),
        ),
    ]
