# Generated by Django 2.2.14 on 2023-12-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20231201_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='product_id',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='comment',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
