# Generated by Django 2.2.14 on 2023-12-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20231202_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='product_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
